[package]
name = "blog-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
blog-client = { path = "../blog-client" }
anyhow = { workspace = true }
clap = { version = "4", features = ["derive"] }
