server:
  http_port: 3000
  grpc_port: 50051
  host: 127.0.0.1
  log_level: info
  white_list:
    - "http://localhost:8080"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "blog"
  require_ssl: false
